"""baseline schema

Revision ID: 20260622_0001
Revises:
Create Date: 2026-06-22 02:24:38.989966
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260622_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Databases created before Alembic already contain the core schema.
    # Adopt them without recreating tables, adding only the snapshot table
    # introduced together with this baseline.
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table("usuarios"):
        if not inspector.has_table("vmware_inventory_snapshots"):
            op.create_table('vmware_inventory_snapshots',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('hypervisor_id', sa.Integer(), nullable=False),
            sa.Column('discovered_vms', sa.JSON(), nullable=False),
            sa.Column('source', sa.String(length=30), nullable=False),
            sa.Column('collected_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['hypervisor_id'], ['hypervisors.id'], ),
            sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_vmware_inventory_snapshots_collected_at'), 'vmware_inventory_snapshots', ['collected_at'], unique=False)
            op.create_index(op.f('ix_vmware_inventory_snapshots_hypervisor_id'), 'vmware_inventory_snapshots', ['hypervisor_id'], unique=False)
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('resource_pattern', sa.String(length=150), nullable=False),
    sa.Column('minimum_severity', sa.String(length=20), nullable=False),
    sa.Column('ticket_priority', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_assign_department', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('backup_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('protected_resource', sa.String(length=150), nullable=False),
    sa.Column('backup_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('repository', sa.String(length=150), nullable=False),
    sa.Column('offsite_target', sa.String(length=150), nullable=True),
    sa.Column('rto_hours', sa.Integer(), nullable=False),
    sa.Column('rpo_hours', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.String(length=80), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('last_restore_test', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('sede', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_contrato', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_ruc'), 'clientes', ['ruc'], unique=True)
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=50), nullable=False),
    sa.Column('sede', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleados_dni'), 'empleados', ['dni'], unique=True)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('serie', sa.String(length=100), nullable=False),
    sa.Column('sede', sa.String(length=50), nullable=False),
    sa.Column('vlan', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.create_table('monitoring_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('resource', sa.String(length=150), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('provenance', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_metrics_created_at'), 'monitoring_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_metric'), 'monitoring_metrics', ['metric'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_resource'), 'monitoring_metrics', ['resource'], unique=False)
    op.create_table('security_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('last_audit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('cidr', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('hypervisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('management_ip', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('ram_percent', sa.Float(), nullable=False),
    sa.Column('datastore_percent', sa.Float(), nullable=False),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('vmnics_up', sa.Integer(), nullable=False),
    sa.Column('vmnics_down', sa.Integer(), nullable=False),
    sa.Column('vmkernel', sa.String(length=120), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monitoring_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monitoring_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('resource', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_events_created_at'), 'monitoring_events', ['created_at'], unique=False)
    op.create_table('network_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_site_id', sa.Integer(), nullable=False),
    sa.Column('target_site_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('provenance', sa.String(length=30), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['target_site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('physical_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('device_type', sa.String(length=30), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('management_port', sa.Integer(), nullable=False),
    sa.Column('management_vlan', sa.String(length=30), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_index(op.f('ix_physical_devices_name'), 'physical_devices', ['name'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hypervisor_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('power_state', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Float(), nullable=False),
    sa.Column('disk_gb', sa.Float(), nullable=False),
    sa.Column('vlan', sa.String(length=30), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('allow_technician_power', sa.Boolean(), nullable=False),
    sa.Column('last_state_change', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hypervisor_id'], ['hypervisors.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_machines_name'), 'virtual_machines', ['name'], unique=True)
    op.create_table('vmware_inventory_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypervisor_id', sa.Integer(), nullable=False),
    sa.Column('discovered_vms', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hypervisor_id'], ['hypervisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vmware_inventory_snapshots_collected_at'), 'vmware_inventory_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_vmware_inventory_snapshots_hypervisor_id'), 'vmware_inventory_snapshots', ['hypervisor_id'], unique=False)
    op.create_table('it_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('service_type', sa.String(length=60), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('sla_target', sa.Float(), nullable=False),
    sa.Column('uptime_percent', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('exposure', sa.String(length=20), nullable=False),
    sa.Column('vlan', sa.String(length=30), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['virtual_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_it_services_name'), 'it_services', ['name'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vlan', sa.String(length=30), nullable=True),
    sa.Column('affected_resource', sa.String(length=150), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['physical_devices.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['it_services.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['virtual_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('availability_target', sa.Float(), nullable=False),
    sa.Column('response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('monthly_fee', sa.Float(), nullable=False),
    sa.Column('penalty_percent', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['it_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sla_contracts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_it_services_name'), table_name='it_services')
    op.drop_table('it_services')
    op.drop_index(op.f('ix_vmware_inventory_snapshots_hypervisor_id'), table_name='vmware_inventory_snapshots')
    op.drop_index(op.f('ix_vmware_inventory_snapshots_collected_at'), table_name='vmware_inventory_snapshots')
    op.drop_table('vmware_inventory_snapshots')
    op.drop_index(op.f('ix_virtual_machines_name'), table_name='virtual_machines')
    op.drop_table('virtual_machines')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_physical_devices_name'), table_name='physical_devices')
    op.drop_table('physical_devices')
    op.drop_table('network_links')
    op.drop_index(op.f('ix_monitoring_events_created_at'), table_name='monitoring_events')
    op.drop_table('monitoring_events')
    op.drop_table('monitoring_agents')
    op.drop_table('hypervisors')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('security_controls')
    op.drop_index(op.f('ix_monitoring_metrics_resource'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_metric'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_created_at'), table_name='monitoring_metrics')
    op.drop_table('monitoring_metrics')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_empleados_dni'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_clientes_ruc'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_table('backup_jobs')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
